import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

function Profile({ user }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to your profile.</h1>
        <p className={styles.description}>Here are your details:</p>
        <p>{JSON.stringify(user)}</p>
      </main>
    </div>
  );
}

export const getServerSideProps = withPageAuthRequired();

export default Profile;